# Generated by Django 3.1.1 on 2020-10-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='details',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
