# Generated by Django 3.1 on 2020-10-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_auto_20200927_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickup',
            name='employee_name',
        ),
    ]
